# Generated by Django 5.1.4 on 2024-12-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_product_price_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='Product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
