# Generated by Django 5.1.4 on 2024-12-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
