# Generated by Django 5.1.2 on 2024-10-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_osoba_data_dodania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='plec',
        ),
    ]
