# Generated by Django 5.1.2 on 2024-10-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_osoba_plec'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Mezczyzna')], default=1),
        ),
    ]
