###
# @non-worker
GET http://127.0.0.1:8000/products/
Accept: application/json
Authorization: Token d011dbf2f10572afd2f8d0a36a1b44951155694f

###
# @worker
GET http://127.0.0.1:8000/products/
Accept: application/json
Authorization: Token 05ea8810ba6d8030f1582231cc95a45e13658680

###
# @admin
GET http://127.0.0.1:8000/products/
Accept: application/json
Authorization: Token 3dbdf2504dabe491df69bc89687a890b2b5f9c73

###
# @notoken
GET http://127.0.0.1:8000/products/
Accept: application/json